[package]
productName = "qSpider"
version = "../package.json"

[build]
distDir = "../dist/apps/player-desktop"
devPath = "http://localhost:4200"
beforeDevCommand = "npm run serve:desktop"
beforeBuildCommand = "npm run build:desktop"
withGlobalTauri = false

[tauri.cli]
description = "qSpider CLI"

[[tauri.cli.args]]
name = "filePath"
index = 1
takesValue = true
description = "Game file to open"

[[tauri.cli.args]]
short = "f"
name = "file"
takesValue = true
description = "Game file to open"

[tauri.bundle]
active = true
targets = "all"
identifier = "org.qsp.qspider"
publisher = "QSPFoundation"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico",
]
resources = []
externalBin = []
copyright = ""
category = "Entertainment"
shortDescription = "Player to run QSP games"
longDescription = ""

[tauri.bundle.deb]
depends = []

[tauri.updater]
active = true
endpoints = ["https://qspfoundation.github.io/qspider/updater.json"]
dialog = true
pubkey = "dW50cnVzdGVkIGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXk6IDE1RjFFRUMxODU0MjE5NUYKUldSZkdVS0Z3ZTd4RlVJQkZhQURQb0VJTVJ0QnI2NVZNOTJMQm5qdzZYRjNYa1ppVmZ0SFpndHQK"

[tauri.allowlist]
all = true
fs = { scope = ["$APPDATA/**", "$APPDATA/*", "$APPDATA"] }

[[tauri.windows]]
title = "qSpider"
width = 1024
height = 768
center = true
resizable = true
fullscreen = false
visible = false

[tauri.security]
freezePrototype = false
